from __future__ import annotations

import subprocess
from unittest.mock import patch, MagicMock

import pytest

from dependabot_plus.queue.models import (
    Ecosystem,
    QueueItem,
    RiskLevel,
    SandboxResult,
    StaticFindings,
    Verdict,
)
from dependabot_plus.report.github import format_report, post_report


def _make_item() -> QueueItem:
    return QueueItem(
        repo="owner/repo",
        pr_number=99,
        ecosystem=Ecosystem.NPM,
        package_name="lodash",
        old_version="4.17.20",
        new_version="4.17.21",
    )


# ---------------------------------------------------------------------------
# format_report
# ---------------------------------------------------------------------------


class TestFormatReport:
    def test_low_risk_no_findings(self):
        item = _make_item()
        verdict = Verdict(
            risk_level=RiskLevel.LOW,
            static_findings=StaticFindings(suspicious_patterns=[], risk_level=RiskLevel.LOW),
            dynamic_findings=SandboxResult(
                install_exit_code=0,
                install_logs="",
                file_accesses=[],
                network_attempts=[],
            ),
            summary="No issues found.",
        )
        report = format_report(item, verdict)

        assert "LOW" in report
        assert "lodash" in report
        assert "4.17.20" in report
        assert "4.17.21" in report
        assert "No issues found." in report
        assert "Install: Succeeded" in report
        # Should NOT contain findings sections
        assert "Static Analysis Findings" not in report
        assert "Canary File Access" not in report
        assert "Network Activity" not in report

    def test_high_risk_with_canary_file_accesses(self):
        item = _make_item()
        verdict = Verdict(
            risk_level=RiskLevel.HIGH,
            static_findings=StaticFindings(
                suspicious_patterns=["eval() usage in postinstall"],
                risk_level=RiskLevel.HIGH,
            ),
            dynamic_findings=SandboxResult(
                install_exit_code=0,
                install_logs="",
                file_accesses=[
                    {"raw": "/etc/passwd"},
                    {"raw": "/home/user/.ssh/id_rsa"},
                ],
                network_attempts=[],
            ),
            summary="Suspicious behaviour detected.",
        )
        report = format_report(item, verdict)

        assert "HIGH" in report
        assert "Static Analysis Findings" in report
        assert "eval() usage in postinstall" in report
        assert "Canary File Access Detected" in report
        assert "/etc/passwd" in report
        assert "/home/user/.ssh/id_rsa" in report

    def test_failed_install(self):
        item = _make_item()
        verdict = Verdict(
            risk_level=RiskLevel.MEDIUM,
            static_findings=StaticFindings(),
            dynamic_findings=SandboxResult(
                install_exit_code=1,
                install_logs="npm ERR! 404 Not Found",
                file_accesses=[],
                network_attempts=[],
            ),
            summary="Install failed.",
        )
        report = format_report(item, verdict)

        assert "Install: Failed (exit code 1)" in report
        assert "npm ERR! 404 Not Found" in report
        assert "<details>" in report

    def test_network_activity(self):
        item = _make_item()
        verdict = Verdict(
            risk_level=RiskLevel.HIGH,
            static_findings=StaticFindings(),
            dynamic_findings=SandboxResult(
                install_exit_code=0,
                install_logs="",
                file_accesses=[],
                network_attempts=[
                    {"type": "http", "method": "POST", "host": "evil.com", "path": "/steal", "body_preview": "secret_data"},
                    {"type": "dns", "query": "A? evil.com"},
                    {"type": "tcp", "destination": "1.2.3.4.443"},
                ],
            ),
            summary="Outbound connection detected.",
        )
        report = format_report(item, verdict)

        assert "HTTP Requests" in report
        assert "POST" in report
        assert "evil.com" in report
        assert "secret_data" in report
        assert "DNS Lookups" in report
        assert "TCP connections" in report

    def test_report_ends_with_signature(self):
        item = _make_item()
        verdict = Verdict(
            risk_level=RiskLevel.LOW,
            static_findings=StaticFindings(),
            dynamic_findings=SandboxResult(
                install_exit_code=0, install_logs=""
            ),
            summary="Clean.",
        )
        report = format_report(item, verdict)
        assert report.strip().endswith("*Generated by DependabotPlus*")


# ---------------------------------------------------------------------------
# post_report
# ---------------------------------------------------------------------------


class TestPostReport:
    def test_calls_gh_with_correct_arguments(self):
        item = _make_item()
        verdict = Verdict(
            risk_level=RiskLevel.LOW,
            static_findings=StaticFindings(),
            dynamic_findings=SandboxResult(
                install_exit_code=0, install_logs=""
            ),
            summary="All clear.",
        )

        with patch("dependabot_plus.report.github.subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=0)
            post_report(item, verdict)

        mock_run.assert_called_once()
        call_args = mock_run.call_args
        cmd = call_args[0][0]

        assert cmd[0] == "gh"
        assert cmd[1] == "pr"
        assert cmd[2] == "comment"
        assert cmd[3] == "99"
        assert "--repo" in cmd
        assert cmd[cmd.index("--repo") + 1] == "owner/repo"
        assert "--body" in cmd
        # The body should be the formatted report
        body = cmd[cmd.index("--body") + 1]
        assert "lodash" in body
        assert "All clear." in body

        # Verify subprocess options
        assert call_args[1]["capture_output"] is True
        assert call_args[1]["text"] is True
        assert call_args[1]["check"] is True

    def test_raises_on_gh_failure(self):
        item = _make_item()
        verdict = Verdict(
            risk_level=RiskLevel.LOW,
            static_findings=StaticFindings(),
            dynamic_findings=SandboxResult(
                install_exit_code=0, install_logs=""
            ),
            summary="Ok.",
        )

        with patch("dependabot_plus.report.github.subprocess.run") as mock_run:
            mock_run.side_effect = subprocess.CalledProcessError(1, "gh")
            with pytest.raises(subprocess.CalledProcessError):
                post_report(item, verdict)
