from __future__ import annotations

import subprocess

from dependabot_plus.queue.models import QueueItem, RiskLevel, Verdict

_RISK_ICONS = {
    RiskLevel.LOW: "🟢",
    RiskLevel.MEDIUM: "🟡",
    RiskLevel.HIGH: "🔴",
    RiskLevel.UNKNOWN: "⚪",
}


def format_report(item: QueueItem, verdict: Verdict) -> str:
    """Format a verdict as a markdown PR comment."""
    icon = _RISK_ICONS.get(verdict.risk_level, "⚪")
    lines = [
        f"## {icon} DependabotPlus Security Analysis",
        "",
        f"**Package:** `{item.package_name}` ({item.ecosystem.value})",
        f"**Version:** `{item.old_version}` → `{item.new_version}`",
        f"**Risk Level:** {icon} **{verdict.risk_level.value.upper()}**",
        "",
        "### Summary",
        verdict.summary,
        "",
    ]

    # Static analysis
    if verdict.static_findings.suspicious_patterns:
        lines.append("### Static Analysis Findings")
        for finding in verdict.static_findings.suspicious_patterns:
            lines.append(f"- {finding}")
        lines.append("")

    # Dynamic analysis
    dynamic = verdict.dynamic_findings
    if dynamic.file_accesses:
        lines.append("### Canary File Access Detected")
        lines.append("")
        lines.append("The following canary files were accessed during install:")
        for access in dynamic.file_accesses:
            raw = access.get("raw", str(access))
            lines.append(f"- `{raw}`")
        lines.append("")

    if dynamic.network_attempts:
        http_reqs = [a for a in dynamic.network_attempts if a.get("type") == "http"]
        dns = [a for a in dynamic.network_attempts if a.get("type") == "dns"]
        tcp = [a for a in dynamic.network_attempts if a.get("type") == "tcp"]

        if http_reqs:
            lines.append("### HTTP Requests")
            lines.append("")
            for r in http_reqs:
                method = r.get("method", "?")
                host = r.get("host", "?")
                path = r.get("path", "/")
                lines.append(f"- **{method}** `{host}{path}`")
                body = r.get("body_preview")
                if body:
                    # Truncate and escape for markdown
                    safe = body[:200].replace("`", "'")
                    lines.append(f"  - Body: `{safe}`")
            lines.append("")

        if dns:
            lines.append("### DNS Lookups")
            lines.append("")
            for a in dns:
                lines.append(f"- `{a.get('query', a)}`")
            lines.append("")

        if tcp:
            lines.append(
                f"<details><summary>TCP connections ({len(tcp)} unique destinations)</summary>\n"
            )
            for a in tcp:
                lines.append(f"- `{a.get('destination', a)}`")
            lines.append("\n</details>")
            lines.append("")

    if dynamic.sudo_attempts:
        lines.append("### Privilege Escalation Attempts")
        lines.append("")
        lines.append("The install script attempted to use `sudo`:")
        for attempt in dynamic.sudo_attempts:
            lines.append(f"- `{attempt}`")
        lines.append("")

    # Install result
    exit_code = dynamic.install_exit_code
    if exit_code == 0:
        lines.append("### Install: Succeeded")
    else:
        lines.append(f"### Install: Failed (exit code {exit_code})")
        if dynamic.install_logs:
            lines.append("")
            lines.append("<details><summary>Install logs</summary>")
            lines.append("")
            lines.append("```")
            lines.append(dynamic.install_logs[-3000:])
            lines.append("```")
            lines.append("</details>")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by DependabotPlus*")

    return "\n".join(lines)


def post_report(item: QueueItem, verdict: Verdict) -> None:
    """Post a security analysis report as a comment on the PR."""
    body = format_report(item, verdict)
    subprocess.run(
        [
            "gh", "pr", "comment",
            str(item.pr_number),
            "--repo", item.repo,
            "--body", body,
        ],
        capture_output=True,
        text=True,
        check=True,
    )


def add_label(repo: str, pr_number: int, label: str) -> None:
    """Add a label to a PR, creating it first if it doesn't exist."""
    # Ensure label exists (no-op if it already does)
    subprocess.run(
        ["gh", "label", "create", label, "--repo", repo,
         "--color", "0E8A16", "--description", "Dependencies vetted by DependabotPlus",
         "--force"],
        capture_output=True, text=True,
    )
    subprocess.run(
        ["gh", "pr", "edit", str(pr_number), "--repo", repo,
         "--add-label", label],
        capture_output=True, text=True, check=True,
    )
