from __future__ import annotations

import subprocess

from dependabot_plus.queue.models import QueueItem, RiskLevel, Verdict

_RISK_ICONS = {
    RiskLevel.LOW: "🟢",
    RiskLevel.MEDIUM: "🟡",
    RiskLevel.HIGH: "🔴",
    RiskLevel.UNKNOWN: "⚪",
}


def format_report(item: QueueItem, verdict: Verdict) -> str:
    """Format a verdict as a markdown PR comment."""
    icon = _RISK_ICONS.get(verdict.risk_level, "⚪")
    lines = [
        f"## {icon} DependabotPlus Security Analysis",
        "",
        f"**Package:** `{item.package_name}` ({item.ecosystem.value})",
        f"**Version:** `{item.old_version}` → `{item.new_version}`",
        f"**Risk Level:** {icon} **{verdict.risk_level.value.upper()}**",
        "",
        "### Summary",
        verdict.summary,
        "",
    ]

    # Static analysis
    if verdict.static_findings.suspicious_patterns:
        lines.append("### Static Analysis Findings")
        for finding in verdict.static_findings.suspicious_patterns:
            lines.append(f"- {finding}")
        lines.append("")

    # Dynamic analysis
    dynamic = verdict.dynamic_findings
    if dynamic.file_accesses:
        lines.append("### Canary File Access Detected")
        lines.append("")
        lines.append("The following canary files were accessed during install:")
        for access in dynamic.file_accesses:
            raw = access.get("raw", str(access))
            lines.append(f"- `{raw}`")
        lines.append("")

    if dynamic.network_attempts:
        lines.append("### Network Activity Detected")
        lines.append("")
        dns = [a for a in dynamic.network_attempts if a.get("type") == "dns"]
        tcp = [a for a in dynamic.network_attempts if a.get("type") == "tcp"]
        http = [a for a in dynamic.network_attempts if a.get("type") == "http"]
        if dns:
            lines.append("**DNS lookups:**")
            for a in dns:
                lines.append(f"- `{a.get('query', a)}`")
        if tcp:
            lines.append("**TCP connections:**")
            for a in tcp:
                lines.append(f"- `{a.get('destination', a)}`")
        if http:
            lines.append("**HTTP requests:**")
            for a in http:
                lines.append(f"- `{a.get('host', a)}`")
        lines.append("")

    # Install result
    exit_code = dynamic.install_exit_code
    if exit_code == 0:
        lines.append("### Install: Succeeded")
    else:
        lines.append(f"### Install: Failed (exit code {exit_code})")
        if dynamic.install_logs:
            lines.append("")
            lines.append("<details><summary>Install logs</summary>")
            lines.append("")
            lines.append("```")
            lines.append(dynamic.install_logs[-3000:])
            lines.append("```")
            lines.append("</details>")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by DependabotPlus*")

    return "\n".join(lines)


def post_report(item: QueueItem, verdict: Verdict) -> None:
    """Post a security analysis report as a comment on the PR."""
    body = format_report(item, verdict)
    subprocess.run(
        [
            "gh", "pr", "comment",
            str(item.pr_number),
            "--repo", item.repo,
            "--body", body,
        ],
        capture_output=True,
        text=True,
        check=True,
    )
